/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesCoinflipRouteImport } from './routes/games/coinflip'
import { Route as ApiVerifyRouteImport } from './routes/api/verify'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as ApiXamanSigninRouteImport } from './routes/api/xaman.signin'
import { Route as ApiXamanSigninStatusRouteImport } from './routes/api/xaman.signin.status'
import { Route as ApiPublicCronPollDepositsRouteImport } from './routes/api/public/cron/poll-deposits'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCoinflipRoute = GamesCoinflipRouteImport.update({
  id: '/games/coinflip',
  path: '/games/coinflip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyRoute = ApiVerifyRouteImport.update({
  id: '/api/verify',
  path: '/api/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiXamanSigninRoute = ApiXamanSigninRouteImport.update({
  id: '/api/xaman/signin',
  path: '/api/xaman/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXamanSigninStatusRoute = ApiXamanSigninStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiXamanSigninRoute,
} as any)
const ApiPublicCronPollDepositsRoute =
  ApiPublicCronPollDepositsRouteImport.update({
    id: '/api/public/cron/poll-deposits',
    path: '/api/public/cron/poll-deposits',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/verify': typeof ApiVerifyRoute
  '/games/coinflip': typeof GamesCoinflipRoute
  '/api/xaman/signin': typeof ApiXamanSigninRouteWithChildren
  '/api/public/cron/poll-deposits': typeof ApiPublicCronPollDepositsRoute
  '/api/xaman/signin/status': typeof ApiXamanSigninStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/verify': typeof ApiVerifyRoute
  '/games/coinflip': typeof GamesCoinflipRoute
  '/api/xaman/signin': typeof ApiXamanSigninRouteWithChildren
  '/api/public/cron/poll-deposits': typeof ApiPublicCronPollDepositsRoute
  '/api/xaman/signin/status': typeof ApiXamanSigninStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/api/verify': typeof ApiVerifyRoute
  '/games/coinflip': typeof GamesCoinflipRoute
  '/api/xaman/signin': typeof ApiXamanSigninRouteWithChildren
  '/api/public/cron/poll-deposits': typeof ApiPublicCronPollDepositsRoute
  '/api/xaman/signin/status': typeof ApiXamanSigninStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify'
    | '/wallet'
    | '/api/verify'
    | '/games/coinflip'
    | '/api/xaman/signin'
    | '/api/public/cron/poll-deposits'
    | '/api/xaman/signin/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify'
    | '/wallet'
    | '/api/verify'
    | '/games/coinflip'
    | '/api/xaman/signin'
    | '/api/public/cron/poll-deposits'
    | '/api/xaman/signin/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/leaderboard'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify'
    | '/_authenticated/wallet'
    | '/api/verify'
    | '/games/coinflip'
    | '/api/xaman/signin'
    | '/api/public/cron/poll-deposits'
    | '/api/xaman/signin/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyRoute: typeof VerifyRoute
  ApiVerifyRoute: typeof ApiVerifyRoute
  GamesCoinflipRoute: typeof GamesCoinflipRoute
  ApiXamanSigninRoute: typeof ApiXamanSigninRouteWithChildren
  ApiPublicCronPollDepositsRoute: typeof ApiPublicCronPollDepositsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/coinflip': {
      id: '/games/coinflip'
      path: '/games/coinflip'
      fullPath: '/games/coinflip'
      preLoaderRoute: typeof GamesCoinflipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify': {
      id: '/api/verify'
      path: '/api/verify'
      fullPath: '/api/verify'
      preLoaderRoute: typeof ApiVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/xaman/signin': {
      id: '/api/xaman/signin'
      path: '/api/xaman/signin'
      fullPath: '/api/xaman/signin'
      preLoaderRoute: typeof ApiXamanSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/xaman/signin/status': {
      id: '/api/xaman/signin/status'
      path: '/status'
      fullPath: '/api/xaman/signin/status'
      preLoaderRoute: typeof ApiXamanSigninStatusRouteImport
      parentRoute: typeof ApiXamanSigninRoute
    }
    '/api/public/cron/poll-deposits': {
      id: '/api/public/cron/poll-deposits'
      path: '/api/public/cron/poll-deposits'
      fullPath: '/api/public/cron/poll-deposits'
      preLoaderRoute: typeof ApiPublicCronPollDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiXamanSigninRouteChildren {
  ApiXamanSigninStatusRoute: typeof ApiXamanSigninStatusRoute
}

const ApiXamanSigninRouteChildren: ApiXamanSigninRouteChildren = {
  ApiXamanSigninStatusRoute: ApiXamanSigninStatusRoute,
}

const ApiXamanSigninRouteWithChildren = ApiXamanSigninRoute._addFileChildren(
  ApiXamanSigninRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyRoute: VerifyRoute,
  ApiVerifyRoute: ApiVerifyRoute,
  GamesCoinflipRoute: GamesCoinflipRoute,
  ApiXamanSigninRoute: ApiXamanSigninRouteWithChildren,
  ApiPublicCronPollDepositsRoute: ApiPublicCronPollDepositsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
